config/routes.rb
Rails.application.routes.draw do
  get 'presenter', to: 'main#presenter'
  get 'screen', to: 'main#screen'
  get 'atendee', to: 'main#atendee'
  get 'print', to: 'main#print'
  get 'slides', to: 'main#slides'
  root to: 'main#atendee'

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/main_controller.rb
require 'ovto_show/slide_parser'

class MainController < ApplicationController
  skip_before_action :require_login, only: %w(screen atendee print slides)
  before_action :set_slides

  def screen
    render :index
  end

  def presenter
    require_login
    render :index
  end

  def atendee
    render :index
  end

  def print
    render :index
  end

  # 
  # APIs
  #

  def slides
    respond_to do |format|
      format.json
    end
  end

  private

  def set_slides
    @parser ||= OvtoShow::SlideParser.new
    @slides = @parser.parse(File.read("#{Rails.root}/data/slide.txt"))
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      cookies.encrypted[:user_id] = current_user.id
      redirect_back_or_to('/presenter', notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    cookies.encrypted[:user_id] = nil
    redirect_to(:login, notice: 'Logged out!')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OvtoShow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>
    <% if action_name == "presenter" %>
      <div><%= link_to "Log out", logout_path, method: :delete %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<div id='ovto-app'></div>
<div id='ovtoshow-slides' style='display: none'><%== @slides.to_json %></div>

<%= opal_tag do %>
  app = OvtoApp.instance
  app.run(id: 'ovto-app')
  app.actions.set_mode(mode: '<%= action_name %>')
  # Does not work(why?)
  # app.actions.set_slides(slides: `<%== @slides.to_json %>`))
  json_str = nil
  %x{
    json_str = document.querySelector('#ovtoshow-slides').textContent;
    //window.Opal.OvtoApp.slides = JSON.parse(json_str);
  }
  app.actions.set_slides(slides: JSON.parse(json_str))
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= check_box_tag :remember, params[:remember], true %>
    <%= label_tag :remember %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to "Logout", :logout, method: :post %>